version: '3.3'
services:
  db:
    network_mode: bridge
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./ep1.sql:/docker-entrypoint-initdb.d/create_tables.sql
volumes:
  db:
    driver: local

# Subir: docker-compose up

# Matar: docker-compose down
# Matar tudo: docker-compose down --volumes

# Pegar ID do container: docker ps

# Entrar no docker: docker exec -ti <id> bash

# Logar postgres: psql -U postgres

# Rodar queries (nao esquecer do ;)