version: '3.3'
services:
  db:
    network_mode: bridge
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./cria.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./popula.sql:/docker-entrypoint-initdb.d/populate_tables.sql
volumes:
  db:
    driver: local
